package com.hexf11.gatewave

internal object ClashConfigGenerator {
    @JvmStatic
    fun generate(serverAddress: String, socksPort: Int, udpEnabled: Boolean): String = """
        # Generated by Gatewave
        mixed-port: 7890
        allow-lan: true
        mode: rule
        log-level: info
        ipv6: false

        dns:
          enable: true
          ipv6: false
          enhanced-mode: fake-ip
          default-nameserver:
            - 223.5.5.5
            - 119.29.29.29
          nameserver:
            - https://dns.alidns.com/dns-query
            - https://doh.pub/dns-query
          fallback:
            - https://dns.google/dns-query
            - https://cloudflare-dns.com/dns-query
          fallback-filter:
            geoip: true
            geoip-code: CN
            ipcidr:
              - 240.0.0.0/4

        proxies:
          - name: Gatewave
            type: socks5
            server: $serverAddress
            port: $socksPort
            udp: $udpEnabled

        proxy-groups:
          - name: 节点选择
            type: select
            proxies:
              - Gatewave
              - DIRECT
          - name: 漏网之鱼
            type: select
            proxies:
              - Gatewave
              - DIRECT

        rules:
          - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
          - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
          - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
          - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
          - IP-CIDR,169.254.0.0/16,DIRECT,no-resolve
          - IP-CIDR6,::1/128,DIRECT,no-resolve
          - IP-CIDR6,fc00::/7,DIRECT,no-resolve
          - IP-CIDR6,fe80::/10,DIRECT,no-resolve
          - DOMAIN-SUFFIX,google.com,节点选择
          - DOMAIN-SUFFIX,gstatic.com,节点选择
          - DOMAIN-SUFFIX,googleapis.com,节点选择
          - DOMAIN-SUFFIX,youtube.com,节点选择
          - DOMAIN-SUFFIX,ytimg.com,节点选择
          - DOMAIN-SUFFIX,openai.com,节点选择
          - DOMAIN-SUFFIX,chatgpt.com,节点选择
          - DOMAIN-SUFFIX,github.com,节点选择
          - DOMAIN-SUFFIX,githubusercontent.com,节点选择
          - DOMAIN-SUFFIX,twitter.com,节点选择
          - DOMAIN-SUFFIX,x.com,节点选择
          - DOMAIN-SUFFIX,twimg.com,节点选择
          - DOMAIN-SUFFIX,telegram.org,节点选择
          - DOMAIN-SUFFIX,t.me,节点选择
          - DOMAIN-SUFFIX,cn,DIRECT
          - GEOIP,CN,DIRECT
          - MATCH,漏网之鱼
    """.trimIndent() + "\n"
}
